- name: Setup Jenkins 
  hosts: node1
  become: true
  
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-1.8.0-openjdk
    jenkins_version: "2.164"

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins